In [2]:
#section 5 NumPy Library

In [4]:
#23 The Power of NumPy

In [6]:
range(0,5)

range(0, 5)

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [ ]:
#multiplying 2 lists

In [10]:
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]

In [12]:
list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [16]:
new_list=[]
for i in range (0,len(list1)):
    x=list1[i]*list2[i]
    new_list.append(x)
print(new_list)

[2, 12, 30, 56, 90]


In [18]:
#multiplying 2 lists using NumPy

In [20]:
import numpy as np

In [22]:
x=np.array([1,3,5,7,9])
y=np.array([2,4,6,8,10])

In [24]:
print(type(x))

<class 'numpy.ndarray'>


In [26]:
x*y

array([ 2, 12, 30, 56, 90])

In [28]:
#25 Creating NumPy Array with the Array() function

In [30]:
import numpy as np

In [32]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [34]:
variable=[5.8,9,7,5]

In [46]:
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [48]:
new_variable=np.array([5.8,9,7,5])

In [50]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [52]:
new_variable2=np.array([5.8,9,7,5],dtype="int")
new_variable2

array([5, 9, 7, 5])

In [ ]:
#26 Creating NumPy Array with the Zeros() function

In [68]:
import numpy as np

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((3,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [76]:
#27 Creating NumPy Array with the Ones() function

In [78]:
import numpy as np

In [80]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
np.ones((3,4,5),dtype="int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [84]:
#28 Creating NumPy Array with the full() function

In [86]:
import numpy as np

In [88]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [90]:
np.full((2,3),6,dtype="float")

array([[6., 6., 6.],
       [6., 6., 6.]])

In [92]:
#29 Creating NumPy Array with the arange() function

In [3]:
import numpy as np

In [9]:
np.arange(3)

array([0, 1, 2])

In [17]:
var=np.arange(3,10,dtype="int")

In [19]:
var

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
type(var)

numpy.ndarray

In [23]:
#30 Creating NumPy Array with the eye() function

In [25]:
import numpy as np

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [31]:
np.eye(3,2,dtype="bool")

array([[ True, False],
       [False,  True],
       [False, False]])

In [33]:
#31 Creating NumPy Array with the linspace() function

In [35]:
import numpy as np

In [37]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [39]:
np.linspace(10,30,5,dtype="int")

array([10, 15, 20, 25, 30])

In [41]:
#32 Creating NumPy Array with the random() function

In [43]:
import numpy as np

In [45]:
#rand function
np.random.rand(5)

array([0.48499953, 0.74061963, 0.31171903, 0.48314257, 0.3692235 ])

In [47]:
np.random.rand(2,3)

array([[0.29613827, 0.91711498, 0.94173108],
       [0.44448983, 0.71523913, 0.04639366]])

In [53]:
#randn function
np.random.randn(5)

array([-1.14057777,  0.02928887, -0.56784772,  0.42923761,  0.59863594])

In [55]:
np.random.randn(2,3)

array([[ 0.12873125,  1.74408169,  0.76367377],
       [-1.31189247, -0.20525302,  2.23328147]])

In [57]:
#random.normal function
np.random.normal(20,5,(2,3))

array([[16.34593941, 24.05973972, 17.96841848],
       [27.27998301, 10.01759963, 22.96125252]])

In [59]:
#randint function
np.random.randint(0,10,(2,3))

array([[7, 0, 1],
       [5, 2, 9]])

In [61]:
#33 Properties of Numpy array

In [63]:
import numpy as np

In [65]:
matrix=np.random.randint(10,50,(5,4))

In [67]:
matrix

array([[21, 30, 36, 35],
       [11, 13, 42, 47],
       [10, 17, 24, 14],
       [28, 47, 40, 19],
       [28, 44, 20, 14]])

In [69]:
matrix.ndim

2

In [71]:
matrix.shape

(5, 4)

In [73]:
matrix.size

20

In [75]:
matrix.dtype

dtype('int32')

In [81]:
matrix1=np.random.randint(10,50,(2,2))
matrix1

array([[44, 26],
       [45, 36]])

In [83]:
matrix1.dtype

dtype('int32')

In [85]:
#Reshaping a NumPy array:Reshape() function

In [87]:
import numpy as np

In [89]:
example=np.arange(1,16)

In [91]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
example.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [97]:
array=example.reshape((1,15))
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [99]:
example.ndim

1

In [101]:
array.ndim

2

In [103]:
example.reshape((3,4))

ValueError: cannot reshape array of size 15 into shape (3,4)

In [105]:
example.reshape((5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [107]:
array.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [109]:
array.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [111]:
#35 Identifying the largest element of Numpy array using max() and argmax() function

In [113]:
import numpy as np

In [115]:
array=np.random.randint(0,50,10)

In [117]:
array

array([35, 36, 30, 48, 40, 12, 35,  3, 13, 22])

In [121]:
array.max()

48

In [123]:
array.argmax()

3

In [125]:
array2=array.reshape(2,5)

In [127]:
array2

array([[35, 36, 30, 48, 40],
       [12, 35,  3, 13, 22]])

In [131]:
array2.max()

48

In [135]:
array3=np.random.randint(0,50,(3,4))
array3

array([[ 1, 18,  7, 28],
       [48, 17, 31,  6],
       [44,  2, 32,  9]])

In [137]:
array3.max()

48

In [139]:
array3.argmax()

4

In [141]:
#36 Detecting the Least element of Numpy array min() and argmin() function

In [155]:
import numpy as np

In [157]:
var=np.random.randint(20,70,10)
var

array([56, 44, 40, 60, 45, 38, 31, 58, 45, 55])

In [159]:
var.min()

31

In [161]:
var.argmin()

6

In [165]:
var2=np.random.randint(20,70,(2,3))

In [167]:
var2

array([[36, 28, 30],
       [28, 40, 53]])

In [169]:
var2.min()

28

In [171]:
var2.argmin()

1

In [2]:
#37 Concatenating NumPy array:concatenate() function

In [4]:
import numpy as np

In [6]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])

In [8]:
arrnp.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.concatenate([array2,array1])

array([5, 6, 7, 8, 1, 2, 3, 4])

In [16]:
array3=np.arange(1,7).reshape((2,3))

In [18]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
array4=np.array([[7,8,9],[10,11,12]])
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.concatenate([array3,array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.concatenate([array3,array4],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
np.concatenate([array1,array4])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [34]:
array5=np.arange(1,11).reshape(5,2)
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
np.concatenate([array3,array5])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [38]:
#38 Splittimg one dimensional numpy array :The Split

In [40]:
import numpy as np

In [42]:
array=np.array([1,3,5,50,50,2,4,6])

In [44]:
np.split(array,(3,5))

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [46]:
x,y,z=np.split(array,(3,5))

In [48]:
x

array([1, 3, 5])

In [50]:
y

array([50, 50])

In [52]:
z

array([2, 4, 6])

In [54]:
np.split(array,4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [56]:
np.split(array,5)

ValueError: array split does not result in an equal division

In [58]:
#39 Splitting 2D NumPy arrays using split() function

In [60]:
import numpy as np

In [62]:
array=np.arange(20).reshape(5,4)

In [64]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
np.split(array,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [68]:
x,y,z=np.split(array,[1,3])

In [70]:
x

array([[0, 1, 2, 3]])

In [72]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [76]:
#to split on column basis

In [78]:
np.split(array,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [80]:
#hsplit() function

In [82]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
np.hsplit(array,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [86]:
np.hsplit(array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [88]:
#vsplit() function

In [90]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [92]:
np.vsplit(array,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [94]:
np.vsplit(array,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [96]:
#40 Sorting numpy arrays:sort() function

In [98]:
import numpy as np

In [100]:
variable=np.array([3,5,1,8,6,2,9])

In [102]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [104]:
np.sort(variable)

array([1, 2, 3, 5, 6, 8, 9])

In [106]:
variable

array([3, 5, 1, 8, 6, 2, 9])

In [108]:
new_variable=np.sort(variable)
new_variable

array([1, 2, 3, 5, 6, 8, 9])

In [110]:
#sorting in 2D arrays

In [112]:
var=np.random.normal(30,10,[4,4])

In [114]:
var

array([[46.62801498, 60.67725938, 33.39322646, 17.43606324],
       [41.08988186,  7.27738787, 37.12500653, 26.24009893],
       [22.84667129, 22.30947414, 33.38345519, 24.22040323],
       [26.32269803, 31.44562206, 29.74520764, 23.44978401]])

In [116]:
np.sort(var,axis=0)

array([[22.84667129,  7.27738787, 29.74520764, 17.43606324],
       [26.32269803, 22.30947414, 33.38345519, 23.44978401],
       [41.08988186, 31.44562206, 33.39322646, 24.22040323],
       [46.62801498, 60.67725938, 37.12500653, 26.24009893]])

In [118]:
np.sort(var,axis=1)

array([[17.43606324, 33.39322646, 46.62801498, 60.67725938],
       [ 7.27738787, 26.24009893, 37.12500653, 41.08988186],
       [22.30947414, 22.84667129, 24.22040323, 33.38345519],
       [23.44978401, 26.32269803, 29.74520764, 31.44562206]])

In [120]:
#41 Indexing NumPy array

In [122]:
import numpy as np

In [124]:
array=np.arange(0,11)

In [126]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
array[4]

4

In [130]:
array[9]

9

In [132]:
array[-2]

9

In [136]:
array[-1]

10

In [142]:
var=np.random.normal(30,10,[3,3])
var

array([[40.03076398, 26.94969014, 42.69065158],
       [24.66135777, 15.09210202, 27.28194021],
       [29.8776427 , 46.15140862, 24.85922242]])

In [144]:
var[0,0]

40.03076397816841

In [146]:
var[2,1]

46.15140862455701

In [154]:
var[-1,-3]

29.877642704388713

In [161]:
var2=np.array(var,dtype="int")

In [164]:
var2

array([[40, 26, 42],
       [24, 15, 27],
       [29, 46, 24]])

In [166]:
#42 Slicing 1D Numpy arrays

In [168]:
import numpy as np

In [172]:
example=np.arange(10,20)
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [174]:
#to slice the number from 12 to 16
example[2:6]

array([12, 13, 14, 15])

In [176]:
example[3::2]

array([13, 15, 17, 19])

In [178]:
example[:7:3]

array([10, 13, 16])

In [180]:
#43 Slicing 2D NumPy arrays

In [182]:
import numpy as np

In [184]:
array=np.arange(30).reshape(6,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [186]:
array[2,:] #return row elements till end

array([10, 11, 12, 13, 14])

In [192]:
array[2,:3]

array([10, 11, 12])

In [194]:
array[2,3]

13

In [202]:
array[2]

array([10, 11, 12, 13, 14])

In [204]:
array[0]

array([0, 1, 2, 3, 4])

In [212]:
#to select column
array[:,2]

array([ 2,  7, 12, 17, 22, 27])

In [214]:
array[1:,2]

array([ 7, 12, 17, 22, 27])

In [216]:
array[:,0]

array([ 0,  5, 10, 15, 20, 25])

In [220]:
#to slice both rows and columns
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [232]:
array[1:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [228]:
array[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [238]:
array[1:4,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [242]:
array[1:4,3]

array([ 8, 13, 18])

In [244]:
array[0::2,0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [246]:
#44 Assigning value to One-Dimensional array

In [248]:
import numpy as np

In [256]:
variable=np.array([0,1,2,3,7,5,6,9,8,9])
variable

array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [258]:
variable[4]=4
variable[7]=7

In [260]:
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
#to assign values by slicing
variable[0:5]=10
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [264]:
variable[5:]

array([5, 6, 7, 8, 9])

In [266]:
variable[5:]=20,30,40,50,60

In [268]:
variable

array([10, 10, 10, 10, 10, 20, 30, 40, 50, 60])

In [270]:
#45 Assigning value to Two-Dimensional array

In [272]:
import numpy as np

In [335]:
example=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [337]:
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [339]:
#to assign 100 instead of 50
example[1,1]=100
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [341]:
example[1,0]=100.5
example

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [347]:
example[0:2]

array([[ 10,  20,  30],
       [100, 100,  60]])

In [349]:
example[0:,2]

array([30, 60, 90])

In [351]:
example[:,2]

array([30, 60, 90])

In [353]:
example[:,2]=10
example

array([[ 10,  20,  10],
       [100, 100,  10],
       [ 70,  80,  10]])

In [355]:
example[0::2]

array([[10, 20, 10],
       [70, 80, 10]])

In [357]:
example[0:2]

array([[ 10,  20,  10],
       [100, 100,  10]])

In [359]:
example[0::2,0:2]

array([[10, 20],
       [70, 80]])

In [361]:
#46 Fancy Indexing of One-dimensional arrays

In [363]:
import numpy as np

In [368]:
fancy=np.arange(0,50,5)
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [370]:
fancy[1]

5

In [373]:
fancy[3]

15

In [375]:
fancy[5]

25

In [377]:
[fancy[1],fancy[3],fancy[5]]

[5, 15, 25]

In [379]:
indexes=[1,3,5]

In [381]:
fancy[indexes]

array([ 5, 15, 25])

In [393]:
array=np.array([1,3,5])
array

array([1, 3, 5])

In [397]:
fancy[array]

array([ 5, 15, 25])

In [399]:
#47 Fancy indexing of Two-dimensional arrays

In [401]:
import numpy as np

In [403]:
variable=np.zeros((10,10),dtype="int")
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [407]:
variable.shape

(10, 10)

In [409]:
variable.shape[0]

10

In [411]:
row=variable.shape[0]

In [415]:
for i in range(row):
    variable[i]=i 
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [417]:
list1=[1,3,5,7]

In [419]:
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [421]:
list2=[8,5,2,7,3]

In [423]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [425]:
#to individually acces the elements in the array

In [429]:
example=np.arange(1,17).reshape((4,4))

In [435]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [443]:
example[[0,3],[1,2]]

array([ 2, 15])

In [459]:
row=[0,2,3,1]
column=[3,0,2,1]

In [463]:
example[row,column]

array([ 4,  9, 15,  6])

In [2]:
#48 Combining Fancy Index with Normal Indexing

In [4]:
import numpy as np

In [8]:
example=np.arange(1,17).reshape((4,4))
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
example[1,[1,3]]

array([6, 8])

In [20]:
example[[0,3],1]

array([ 2, 14])

In [14]:
#49 Combining Fancy Index with Normal Slicing

In [16]:
import numpy as np

In [22]:
example=np.arange(1,17).reshape((4,4))
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
example[0,[1,2]]

array([2, 3])

In [30]:
example[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [36]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [38]:
example[1:2,[1,2]]

array([[6, 7]])

In [40]:
#50 Operations with comparison operator

In [42]:
import numpy as np

In [53]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
array>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [61]:
condition=array<=4
condition

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [65]:
array[condition]

array([1, 2, 3, 4])

In [67]:
new_condition=(array!=8)&(array>=6)

In [69]:
array[new_condition]

array([ 6,  7,  9, 10])

In [71]:
new_condition2=(array!=8)|(array>=6)
array[new_condition2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
#51 Arithmetic operations in numpy

In [75]:
import numpy as np

In [77]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
array -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [81]:
array*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [83]:
array/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [85]:
((array*10)+20)/5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [87]:
array*array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [89]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
np.subtract(array,2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [93]:
np.multiply(array,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [95]:
np.add(array,20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [97]:
np.divide(array,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [99]:
array**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [101]:
np.power(array,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [103]:
np.sqrt(4)

2.0

In [105]:
np.sqrt(100)

10.0

In [107]:
array%5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [109]:
np.mod(array,5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [111]:
np.sin(180)

-0.8011526357338304

In [113]:
np.cos(180)

-0.5984600690578581

In [115]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [117]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [119]:
#52 Statistical operators in NumPy

In [121]:
import numpy as np

In [123]:
array=np.arange(1,11)

In [125]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
np.sum(array)

55

In [129]:
np.mean(array)

5.5

In [131]:
np.median(array)

5.5

In [133]:
np.min(array)

1

In [139]:
np.max(array)

10

In [141]:
np.std(array)

2.8722813232690143

In [143]:
np.var(array)

8.25

In [145]:
np.sqrt(8.25)

2.8722813232690143

In [147]:
np.sqrt(np.var(array))

2.8722813232690143

In [149]:
#53 Solving Second degree equation with numpy

In [151]:
import numpy as np

2X1+X2=5
-3X1+6X2=0


In [162]:
coefficient=np.array([[2,1],[-3,6]])
coefficient

array([[ 2,  1],
       [-3,  6]])

In [164]:
output=np.array([5,0])
output

array([5, 0])

In [166]:
np.linalg.solve(coefficient,output)

array([2., 1.])